apiVersion: v1
kind: Secret
metadata:
  name: minibank-secrets
  namespace: minibank
type: Opaque
stringData:
  # SQL Server credentials
  SA_PASSWORD: "YourStrong@Password123"
  
  # Connection string
  CONNECTION_STRING: "Server=sqlserver-service,1433;Database=minibankdb;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=True"
  
  # JWT signing key (CHANGE THIS!)
  JWT_SIGNING_KEY: "YourSuperSecretKeyThatIsAtLeast32CharactersLongForSecurity123!"