apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minibank-ingress
  namespace: minibank
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - minibank.yourdomain.com
    secretName: minibank-tls
  rules:
  - host: minibank.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minibank-api-service
            port:
              number: 80